version: 2.1

jobs:
  print_hello:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"
  print_world:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"
  print_var:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo "My undercover name is ${TEST_VAR}"

workflows:
  starter-jobs:
    jobs:
      - print_hello
      - print_world:
          requires: 
            - print_hello
      - print_var